spring:
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://houp.c18iugmyoo9t.ap-northeast-2.rds.amazonaws.com:3306/houp
        username: root
        password: 4789131l
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    com.example.houp: info
    org.springframework.web.servlet: info
    org.hibernate.type.descriptor.sql: trace
